export const ACTIONS = {
  GET_PRESTATIONS_LOADING: 'GET_PRESTATIONS_LOADING',
  GET_PRESTATIONS_SUCCESS: 'GET_PRESTATIONS_SUCCESS',
  GET_PRESTATIONS_FAILURE: 'GET_PRESTATIONS_FAILURE',
  SET_THEME: 'SET_THEME'
};
